### ISSUE TITLE
How do I overwrite the controller

### ISSUE THREAD

**Issue by qwel3** [ianneub/kibana-sinatra#11]
How can I overwrite the controller? 
please reply asap its important
I want to create a controller and add the following to it:
before_filter :auth_user

thanks.

**Comment by ianneub** [comment]
Because this is a Rack based plugin, it does not go through the same process as your rails app.

That said you can configure some authentication through the rails routing engine (`routes.rb`).

This is an example that I use with Devise:
```ruby
    authenticate :user, lambda { |u| u.roles.include?('admin') } do
      mount Kibana::Sinatra::Web => '/kibana', :trailing_slash => true
    end
```

See: https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb

**Comment by qwel3** [comment]
thanks
